Graylog2/graylog-plugin-threatintel

- src/main/resources/org.graylog.plugins.graylog-plugin-threatintel/graylog-plugin.properties
Since this plugin is providing pipeline functions, it needs to see other plugins, which is what `isolated=true` prevents.
Fixes https://github.com/Graylog2/graylog2-server/issues/2978
> use shared classloader in graylog-server

- src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java
- src/main/java/org/graylog/plugins/threatintel/migrations/V20170821100300_MigrateOTXAPIToken.java
> Handle absent OTX API key in ThreatIntelPluginConfiguration

- src/main/java/org/graylog/plugins/threatintel/functions/global/GlobalIpLookupFunction.java
This change makes the parameter name of the `threat_intel_lookup_ip` pipeline function consistent with the other IP-related lookup functions, so the parameters can be passed through to the other functions. Without this change, the other functions would get `null` for their `ip_address` parameters.
> Making parameter name consistent so it can be passed through.

- src/main/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapter.java
- src/test/java/org/graylog/plugins/threatintel/adapters/spamhaus/SpamhausEDROPDataAdapterTest.java
This is a simple code cleanup:
* Removing unused refresh interval field from config DTO
* Removing unused constructor parameter
* Defining refresh interval as 12 hours (cache definition for the
lists is currently 24h)
> Cleaning up Spamhaus (E)DROP Data Adapter.

- src/main/java/org/graylog/plugins/threatintel/functions/spamhaus/SpamhausIpLookupFunction.java
The lookup table used in the `spamhaus_lookup_ip()` function should be "spamhaus-drop".
> Fix lookup table used in `spamhaus_lookup_ip()` function

- src/main/java/org/graylog/plugins/threatintel/functions/tor/TorExitNodeLookupFunction.java
The lookup table used in the `tor_lookup()` function should be "tor-exit-node-list".
> Fix lookup table used in `tor_lookup()` function

- pom.xml
- src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginConfiguration.java
- src/main/java/org/graylog/plugins/threatintel/ThreatIntelPluginModule.java
- src/main/java/org/graylog/plugins/threatintel/adapters/otx/OTXDataAdapter.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/AbstractOTXLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/OTXDomainLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/OTXIPLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/migrations/V20170821100300_MigrateOTXAPIToken.java
- src/main/java/org/graylog/plugins/threatintel/tools/Domain.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisDataAdapter.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
- src/main/resources/org/graylog/plugins/threatintel/migrations/V20170815111700_CreateThreatIntelLookupTables-content_pack.json
- src/test/java/org/graylog/plugins/threatintel/adapters/otx/OTXDataAdapterTest.java
- src/test/resources/org/graylog/plugins/threatintel/adapters/otx/otx-IPv4-response.json
- src/web/components/ThreatIntelPluginConfig.jsx
- src/web/components/adapters/otx/OTXAdapterDocumentation.jsx
- src/web/components/adapters/otx/OTXAdapterFieldSet.jsx
- src/web/components/adapters/otx/OTXAdapterSummary.jsx
- src/web/components/adapters/otx/index.jsx
- src/web/components/adapters/whois/WhoisAdapterDocumentation.jsx
- src/web/components/adapters/whois/WhoisAdapterFieldSet.jsx
- src/web/components/adapters/whois/WhoisAdapterSummary.jsx
- src/web/index.jsx
This adds a separate OTX data adaper and uses that one for the OTX API lookup tables to fix several issues and actually makes the OTX features work.
It also fixes the Whois data adapter by adding a client with timeouts.
Notes: This needs to be **cherry-picked into 2.4** once merged
---
**ATTENTION:** Run the following MongoDB shell script via `mongo <filename>.js` to cleanup the existing lookup table/cache/adapter entries. This is only needed if you are running with a previous 2.4-alpha/beta.
```js
var db = connect("localhost:27017/graylog");
db.cluster_config.remove({type: "org.graylog.plugins.threatintel.migrations.V20170815111700_CreateThreatIntelLookupTables.MigrationCompleted"})
db.cluster_config.remove({type: "org.graylog.plugins.threatintel.migrations.V20170821100300_MigrateOTXAPITo …
```
> Fix OTX and Whois data adapter issues

- src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisDataAdapter.java
This should be cherry-picked into 2.4 as well.
> Use .equals() instead of == for object equality condition

- src/main/java/org/graylog/plugins/threatintel/functions/otx/AbstractOTXLookupFunction.java
Fixes Graylog2/graylog2-server#4489
Notice: This needs to be **cherry-picked into 2.4** once merged
> Fix "otx_lookup_domain" pipeline function

- .gitignore
- npm-shrinkwrap.json
Due to a reflux peer dependency problem with react, we ran into an error
and couldn't create a shrinkwrap file for the 2.4.0 release in December.
We now ran into a compatibility problem with a plugin because of changed
dependencies and I tried to create a shrinkwrap file again. It worked
after manually modifying the react peer dependency in the installed
reflux module.
To make sure we have the correct dependency versions from the time of
the 2.4.0 release build, I used the Jenkins workspace directory - which
luckily still existed - to create the npm-shrinkwrap.json file.
> Create npm-shrinkwrap.json files for the 2.4.0 release

- README.md
The field "exit_node_indicated" doesn't exist. The correct field is named "threat_indicated".
> Fix README.md about tor_lookup() function

- src/main/java/org/graylog/plugins/threatintel/functions/otx/AbstractOTXLookupFunction.java
When using the `otx_lookup_ip` and `otx_lookup_domain` in a pipeline rule. All that was being passed back was `otx_threat_indicated`. If a threat was indicated `otx_threat_ids` and `otx_threat_names` are currently not being returned. Just `otx_threat_indicated: true`. This PR fixes that.
> Fix otx threat names ids not populating

- src/web/components/ThreatIntelPluginConfig.jsx
- src/web/components/adapters/abusech/AbuseChRansomAdapterDocumentation.jsx
- src/web/components/adapters/abusech/AbuseChRansomAdapterFieldSet.jsx
- src/web/components/adapters/abusech/AbuseChRansomAdapterSummary.jsx
- src/web/components/adapters/otx/OTXAdapterDocumentation.jsx
- src/web/components/adapters/otx/OTXAdapterFieldSet.jsx
- src/web/components/adapters/otx/OTXAdapterSummary.jsx
- src/web/components/adapters/whois/WhoisAdapterFieldSet.jsx
This PR was generated using the class.js react codemod[1]. It converts all
suitable react components to ES6 classes. If an ES5 component which uses
`React.createClass()` is not suitable for conversion, it uses the
`createReactClass()` helper supplied by the `create-react-class` module.
This change is necessary in preparation for React 16, which removes
`React.createClass()` completely[2]. The codemod used claims to be very
reliable even in corner cases and supposedly `has converted thousands of
components internally at Facebook.`.
[1]: https://github.com/reactjs/react-codemod#explanation-of-the-new-es2015-class-transform-with-property-initializers
[2]: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass
It was run like this:
```
$ jscodeshift …
```
> Removing usages of deprecated React.createClass().

- .github/no-response.yml
Add config needed for no-response bot to automatically close issues that needs-input label has been on for more than 30 days (without a response from issue author).
> Add config for no-response bot

- src/main/java/org/graylog/plugins/threatintel/functions/tor/TorExitNodeLookupFunction.java
Fixes #115 (`tor_lookup` pipeline function always returns a false `threat_indicated` response).
The was previously attempting to parse a boolean response from the Tor Exit Node data adaptor/lookup table (but the table returns the Tor node ID if found). Now, the code correctly return false for a blank/null Tor node ID, and true when an ID of any length is returned.
> Fix bug that always causes a false Tor Exit Node response

- package.json
- yarn.lock
This change is updating the yarn lockfile after upgrading
`graylog-web-plugin`, so all transitive dependencies used across core
and plugins are using the same single version.
Fixes Graylog2/graylog2-server#5520.
> Using pinned versions for shared dependencies from graylog-web-plugin.

- src/main/resources/org/graylog/plugins/threatintel/migrations/V20180906112716_RecreateThreatintelLookupTables-content_pack-spamhaus.json
Fixes Graylog2/graylog2-server#5636
(cherry picked from commit 5945177f9277303a067ac142b07e66fb84c8788a)
> Fix typo in spamhaus content pack to unbreak data adapter installation

- src/main/java/org/graylog/plugins/threatintel/migrations/V20180906112716_RecreateThreatintelLookupTables.java
Prior to this change, the migration used Error instead of an Exception
when the migration did find a matching LookupTable installation already.
This change will use ContentPackException instead so following migrations
can continue to work!
Also we will write the clusterConfig to avoid running into a already found content pack after every restart.
> Use exception instead of Error in migration

- src/web/components/adapters/abusech/AbuseChRansomAdapterFieldSet.jsx
- src/web/components/adapters/otx/OTXAdapterFieldSet.jsx
In all these cases the matchProp needs to be set to "label" and not "value"
because the value contains the object ID or another identifier.
After this, the auto-completion is looking at same data that the user
is seeing.
Refs Graylog2/graylog2-server#5659
> Fix auto-completion in several drop-down fields

- src/main/java/org/graylog/plugins/threatintel/functions/misc/PrivateNetLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/tools/PrivateNet.java
- src/test/java/org/graylog/plugins/threatintel/tools/PrivateNetTest.java
The `in_private_net` function now supports unique local addresses in IPv6 (entire `FC00::/7` subnet)
When something else than an IP address is passed in, the function is now less chatty and does not log the stacktrace anymore. For IP addresses it should never log anything.
fixes #156
fixes Graylog2/graylog2-server#4624
related to #33
> Support IPv6 in in_private_net function, reduce noise on errors

- package.json
This PR unifies the ESLint configuration by extending `eslint-config-graylog` in the `eslintConfig` of the `package.json`.
With Graylog2/graylog2-server#9309 all required settings are now part of `eslint-config-graylog`.
This is also necessary to enable the built-in ESLint editor support.
> Use ESLint settings configured in eslint-config-graylog

- src/main/java/org/graylog/plugins/threatintel/whois/ip/InternetRegistry.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParser.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/WhoisParser.java
- src/test/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParserTest.java
We received reports that the WHOIS data adapter was not providing results for some IP addresses.  Investigation revealed that these IP address had multiple records in ARIN for different Network Types.  When the WHOIS data adapter queried ARIN, it got back the list of record summaries for the multiple results rather than the actual record details.
This change updates the WHOIS data adapter and ARIN parser to better handle this case by ensuring ARIN returns the full records when multiple records are present and using the data from the record with the most preferred Network Type (based on guidance from the Security Team).
This change has been tested in a local instance of Graylog and JUnits have been added to cover the new behavior.
Z-844220
> Update WHOIS plugin to better handle cases with multiple results

- src/main/java/org/graylog/plugins/threatintel/whois/ip/InternetRegistry.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParser.java
- src/main/java/org/graylog/plugins/threatintel/whois/ip/parsers/WhoisParser.java
- src/test/java/org/graylog/plugins/threatintel/whois/ip/parsers/ARINResponseParserTest.java
This is a backport of #180, which updated the WHOIS data adapter to better handle ARIN results with multiple records.  Verified that it works on 4.0:
> Backport updates to WHOIS data adapter

- src/main/java/org/graylog/plugins/threatintel/adapters/abusech/AbuseChRansomAdapter.java
- src/web/components/ThreatIntelPluginConfig.jsx
- src/web/components/adapters/abusech/AbuseChRansomAdapterDocumentation.jsx
- src/web/components/adapters/abusech/AbuseChRansomAdapterSummary.jsx
- src/web/index.jsx
As of Dec 8, 2019, the Ransomware Tracker at abuse.ch was shut down.  This change adds clear warnings throughout the UI that the Ransomware Data Adapter is deprecated and should no longer be used.  It also updates the back end logic to stop the Data Adapter from calling the deprecated endpoints.
Tested locally
Updated data adapter label in drop-down
Added deprecation warning to create/edit page
Added deprecation warning to summary page
Data Adapter shuts down when run
> Deprecate Ransomware Data Adapter

- pom.xml
Refs Graylog2/graylog2-server#11454
> Exclude commons-logging because we are using jcl-over-slf4j

- src/web/components/ThreatIntelPluginConfig.jsx
With this PR we are unifying the button naming of the `ThreatIntelPluginConfig` component.
Related to https://github.com/Graylog2/graylog2-server/pull/13513
> Unify naming of threat intel config buttons.

- src/main/java/org/graylog/plugins/threatintel/adapters/otx/OTXDataAdapter.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/AbstractOTXLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/OTXDomainLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/OTXIPLookupFunction.java
- src/main/java/org/graylog/plugins/threatintel/functions/otx/OTXLookupResult.java
Resolves Graylog2/graylog-plugin-cloud#1046
When OTX API returns an HTTP error code, bubble up the error and log it in the processing failure stream.
How to test: either use a test proxy to manipulate the returned values; or issue OTX requests at a high rate, which will cause the rate limiter to kick in.
/jenkins-pr-deps Graylog2/graylog2-server#13508
> Bubble up HTTP error codes from data adapter
